using Backend.Models;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;

namespace Backend.Services;

public class AiValidationService
{
	private readonly HttpClient _httpClient;
	private readonly string _endpoint;
	private readonly string _apiKey;
	private readonly string _model;

	public AiValidationService(HttpClient httpClient)
	{
		_httpClient = httpClient;

		_endpoint = Environment.GetEnvironmentVariable("AZURE_OPENAI_ENDPOINT")
			?? throw new Exception("AZURE_OPENAI_ENDPOINT is missing.");

		_apiKey = Environment.GetEnvironmentVariable("AZURE_OPENAI_KEY")
			?? throw new Exception("AZURE_OPENAI_KEY is missing.");

		_model = Environment.GetEnvironmentVariable("AZURE_OPENAI_MODEL")
			?? throw new Exception("AZURE_OPENAI_MODEL is missing.");
	}

	public async Task<ValidationResult?> ValidateStartup(Startup startup)
	{
		// Create the prompt that will be sent to the AI
		var prompt = $$"""
            You are an experienced startup and venture capital analyst.

            Analyze the following startup idea.

            Startup name:
            {{startup.Name}}

            Description:
            {{startup.Description}}

            Problem:
            {{startup.Problem}}

            Target customer:
            {{startup.TargetCustomer}}

            Business model:
            {{startup.BusinessModel}}

            Evaluate the startup based on:
            - Problem severity
            - Market potential
            - Differentiation
            - Monetization
            - Technical feasibility
            - Go-to-market potential

            Give each category a score from 1 to 10.

            Also provide:
            - An overall score from 1 to 100
            - A short summary
            - The biggest strength
            - The biggest risk
            - A concrete recommendation

            Return ONLY valid JSON using exactly this structure:

            {
              "overallScore": 0,
              "problemScore": 0,
              "marketScore": 0,
              "differentiationScore": 0,
              "monetizationScore": 0,
              "technicalScore": 0,
              "goToMarketScore": 0,
              "summary": "",
              "biggestStrength": "",
              "biggestRisk": "",
              "recommendation": ""
            }
            """;

		// Create the body that will be sent to the Responses API
		var requestBody = new
		{
			model = _model,
			input = prompt
		};

		// Add the API key to the request
		_httpClient.DefaultRequestHeaders.Authorization =
			new AuthenticationHeaderValue("Bearer", _apiKey);

		// Send request to Azure / Microsoft Foundry
		var response = await _httpClient.PostAsJsonAsync(
			$"{_endpoint}/responses",
			requestBody
		);

		// Read the complete response
		var responseText = await response.Content.ReadAsStringAsync();

		// Stop if Azure returned an error
		if (!response.IsSuccessStatusCode)
		{
			throw new Exception($"AI request failed: {responseText}");
		}

		Console.WriteLine("AI RESPONSE:");
		Console.WriteLine(responseText);

		// Parse the response JSON
		using var json = JsonDocument.Parse(responseText);

		// Get the actual text generated by the AI
		string? outputText = null;

		if (json.RootElement.TryGetProperty("output", out var output))
		{
			foreach (var outputItem in output.EnumerateArray())
			{
				if (!outputItem.TryGetProperty("content", out var content))
				{
					continue;
				}

				foreach (var contentItem in content.EnumerateArray())
				{
					if (contentItem.TryGetProperty("text", out var text))
					{
						outputText = text.GetString();
						break;
					}
				}

				if (outputText != null)
				{
					break;
				}
			}
		}

		if (string.IsNullOrWhiteSpace(outputText))
		{
			return null;
		}

		// Convert the AI's JSON into C# ValidationResult
		var result = JsonSerializer.Deserialize<ValidationResult>(
			outputText,
			new JsonSerializerOptions
			{
				PropertyNameCaseInsensitive = true
			}
		);

		return result;
	}
}